# Generated by Django 2.2.4 on 2021-08-01 04:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='shorturl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(max_length=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('counter', models.IntegerField(default=0)),
                ('chrome', models.IntegerField(default=0)),
                ('firefox', models.IntegerField(default=0)),
                ('safari', models.IntegerField(default=0)),
                ('other_browser', models.IntegerField(default=0)),
                ('android', models.IntegerField(default=0)),
                ('ios', models.IntegerField(default=0)),
                ('window', models.IntegerField(default=0)),
                ('linux', models.IntegerField(default=0)),
                ('mac', models.IntegerField(default=0)),
                ('other_platform', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
